package ru.hse.fcs.tariff.service.interfaces.tariff.dto

enum class MeasurementUnitDto {
    KILOGRAM, GRAM, TON, POUND, OUNCE,
    CUBIC_METER, LITER, MILLILITER, GALLON, QUART, CUBIC_FOOT,
    KG_PER_CUBIC_METER, GRAM_PER_CUBIC_CM, KG_PER_CUBIC_CM, GRAM_PER_CUBIC_METER, POUNDS_PER_CUBIC_FOOT,
    METRE, CENTIMETRE, MILLIMETRE, FOOT, INCH,
    RUB, CNY, USD, EUR
}